if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install()
BiocManager::install("biomaRt")
BiocManager::install("IlluminaHumanMethylation450kanno.ilmn12.hg19")
BiocManager::install("karyoploteR")

if (!requireNamespace("vcfR", quietly = TRUE))
  install.packages("vcfR")
if (!requireNamespace("data.table", quietly = TRUE))
  install.packages("data.table")
if (!requireNamespace("gtools", quietly = TRUE))
  install.packages("gtools")
if (!requireNamespace("stringr", quietly = TRUE))
  install.packages("stringr")
if (!requireNamespace("stringi", quietly = TRUE))
  install.packages("stringi")
if (!requireNamespace("png", quietly = TRUE))
  install.packages("png")
if (!requireNamespace("magick", quietly = TRUE))
  install.packages("magick")